### PR TITLE
chore(firebase_auth_web, firebase_ui_localizations): Upgrades `intl` to 0.18.0

### PR DESCRIPTION
**Pull request by Rexios80**
## Description

Upgrades `intl` to version 0.18.0 in all packages

## Related Issues

N/A

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by russellwheatley** [comment]
@Rexios80 You'll have to update/fix the failing tests before review. Thanks

**Comment by Rexios80** [comment]
Pretty sure things are failing because of flutter 3.7 deprecations which is outside the scope of this PR to fix unless you want it done here

**Comment by russellwheatley** [comment]
We've attempted this before. If the [SDK relies on version](https://github.com/firebase/flutterfire/actions/runs/4093115481/jobs/7058322205#step:6:5811) `0.17`, then we aren't able to proceed as far as I can tell.

**Comment by Rexios80** [comment]
This should be possible when this issue closes: https://github.com/flutter/flutter/issues/117163

**Comment by zeshuaro** [comment]
Currently there seems to be 3 opened PRs attempting to bump the version of `intl`, maybe we should focus on one of them and mark the others as duplicated?
- #10416 
- #10443 
- And this one

Anyway, I just want to propose to relax the version of `intl` to `>=0.17.0 <1.0.0` given that there aren't breaking changes from `0.17.0` to `0.18.0` and to assume that no breaking changes would be released in minor version updates.

When `intl` releases `0.19.0`, the exact same issue will hit again and the proposed range version should get around with it. Also see [this](https://github.com/dart-lang/pub/issues/3747) related issue on Pub about version resolving for `0.x.x` versions.

If we don't feel safe for minor releases of `intl`, can we at least set the version to `>=0.17.0 <0.19.0` so that the Firebase packages will work for both `0.17.0` and `0.18.0`? 

I currently have a project that also uses `intl` and I'm having version resolve issues with a lot of the other packages that also use `intl`. So I would appreciate if a ranged version is used here so that I can gradually transition with the dependencies upgrade on my project while waiting for all the packages to also support the latest version of `intl`.

**Comment by Rexios80** [comment]
Minor version changes on version `0.x.x` are treated as breaking changes. We cannot assume that version `0.19.0` won't have breaking changes, because that's not how the versioning system is designed. What probably needs to happen is that `intl` needs a `1.0.0` release so that minor version changes aren't treated as breaking, but that is well outside the scope of this repo.

We could have a constraint that includes both `0.17.0` and `0.18.0`, but that's probably not worth it since the issue right now is not supporting `0.18.0`. This is just a growing pain with `0.18.0` that when resolved won't matter anymore.

If you're having issues with the `intl` version in your projects, just add it to the `dependency_overrides` for now:

```yaml
dependency_overrides:
  intl: ^0.18.0
```

If there were actually no breaking changes, this will solve your dependency resolution issues.

**Comment by Rexios80** [comment]
https://github.com/dart-lang/intl/issues/522#issuecomment-1445123838

**Comment by Rexios80** [comment]
Seems we are still waiting on a flutter release with `flutter_localizations` that uses `intl: 0.18.0`

**Comment by Rexios80** [comment]
Now CI is failing because of Flutter 3.10 changes. Waiting on https://github.com/firebase/flutterfire/pull/10944

**Comment by Rexios80** [comment]
This should have been dealt with in https://github.com/firebase/flutterfire/pull/10944

**Pull request closed without merging**
