### PR TITLE
feat(web): update to `web: ^1.0.0`

### LINKED ISSUE #13190: [web]: Dependency issue with other package using `web: ^1.0.0`
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Messaging

### Which platforms are affected?

Android, iOS

### Description

its now giving version compatibility issues with others

### Reproducing the issue

Resolving dependencies...
Because no versions of firebase_messaging match >15.0.4 <16.0.0 and firebase_messaging 15.0.4 depends on firebase_messaging_web ^3.8.12, firebase_messaging ^15.0.4 requires firebase_messaging_web ^3.8.12.
Because firebase_messaging_web 3.8.12 depends on web ^0.5.1 and no versions of firebase_messaging_web match >3.8.12 <4.0.0, firebase_messaging_web ^3.8.12 requires web ^0.5.1.
Thus, firebase_messaging ^15.0.4 requires web ^0.5.1.
And because share_plus >=10.0.1 depends on web ^1.0.0, firebase_messaging ^15.0.4 is incompatible with share_plus >=10.0.1.
So, because sportdunia depends on both firebase_messaging ^15.0.4 and share_plus ^10.0.2, version solving failed.
Process finished with exit code 1

### Firebase Core version

3.3.0

### Flutter Version

3.24.0

### Relevant Log Output

```shell
Resolving dependencies...
Because no versions of firebase_messaging match >15.0.4 <16.0.0 and firebase_messaging 15.0.4 depends on firebase_messaging_web ^3.8.12, firebase_messaging ^15.0.4 requires firebase_messaging_web ^3.8.12.
Because firebase_messaging_web 3.8.12 depends on web ^0.5.1 and no versions of firebase_messaging_web match >3.8.12 <4.0.0, firebase_messaging_web ^3.8.12 requires web ^0.5.1.
Thus, firebase_messaging ^15.0.4 requires web ^0.5.1.
And because share_plus >=10.0.1 depends on web ^1.0.0, firebase_messaging ^15.0.4 is incompatible with share_plus >=10.0.1.
So, because sportdunia depends on both firebase_messaging ^15.0.4 and share_plus ^10.0.2, version solving failed.
Process finished with exit code 1
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>Resolving dependencies...
Because no versions of firebase_messaging match >15.0.4 <16.0.0 and firebase_messaging 15.0.4 depends on firebase_messaging_web ^3.8.12, firebase_messaging ^15.0.4 requires firebase_messaging_web ^3.8.12.
Because firebase_messaging_web 3.8.12 depends on web ^0.5.1 and no versions of firebase_messaging_web match >3.8.12 <4.0.0, firebase_messaging_web ^3.8.12 requires web ^0.5.1.
Thus, firebase_messaging ^15.0.4 requires web ^0.5.1.
And because share_plus >=10.0.1 depends on web ^1.0.0, firebase_messaging ^15.0.4 is incompatible with share_plus >=10.0.1.
So, because sportdunia depends on both firebase_messaging ^15.0.4 and share_plus ^10.0.2, version solving failed.
Process finished with exit code 1

### Additional context and comments

_No response_

### PR DESCRIPTION
**Pull request by Lyokone**
## Description

If you want to use this PR early, you can use latest version of FlutterFire CLI
```
dart pub global activate flutterfire_cli 1.0.1-dev.4 --overwrite
flutterfire install git:feat/update-web100
```

## Related Issues

closes #13190

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by mj-shifu** [comment]
Hello @Lyokone, thank you for creating this PR! I tested it out and encountered an issue with phone number authentication:
```
Type '_TypeError' is not a subtype of type 'JSValue' in type cast.
```
After some investigation, I found that changing line 103 of packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_recaptcha_verifier_factory.dart to this resolved the issue for me:

```diff
    _delegate = auth_interop.RecaptchaVerifier(
-      element,
+      element.toJS,
      parameters,
      auth.delegate,
    );
```

Would you be open to including this fix in your PR? This would help me depend on it directly.

**Comment by Lyokone** [comment]
@mj-shifu thanks so much for noticing 👍 We have some dynamic left here and there from the first implementation 😓 I've pushed the fix

**Comment by faheemstepsharp** [comment]
latest version should be used

**Comment by RicharC293** [comment]
How long does it take for this update to be released and available on pub.dev?

**Comment by millerf** [comment]
I would love this to be merged as well. This dependency is blocking quite some of my other dependencies

**Comment by T-P-F** [comment]
@russellwheatley @Salakar this PR unblocks a train of dependency updates that grows longer by the day....

**Comment by mghali1** [comment]
@russellwheatley @Salakar please review this PR asap. A lot of depedencies are being blocked by this. Thank you.

**Comment by millerf** [comment]
Also, side question: I am actually not using flutter on web, so I was wondering if there was a way to prevent this dependency to be used altogether from my project `pubspec.yaml`. It infuriating that a dependency I do not use prevents me to update other things. 
Or maybe I should just override the web dependency!? 🤔🎉

**Comment by amrgetment** [comment]
@millerf Unfortunately, the web package was in beta, but it is now stable 1.0.0, it will have less frequent updates or breaking changes

**Comment by Lyokone** [comment]
Hello, this PR has attracted a lot of attention. We are not ready to force users to upgrade to Dart 3.4 (which is required for us to add support for `web: ^1.0.0`.
We are expecting to make Dart 3.4 required in the coming weeks. You still can depend on this PR or override the `web` version if needed.

**Comment by josh-burton** [comment]
@Lyokone getting some typeerrors in `web_utils` `convertPlatformActionCodeSettings` method: https://github.com/firebase/flutterfire/blob/9c3181dde8e2e999e39eba0bc8cc49d535654966/packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart#L240

The AndroidSettings and IOSSettings fields are not being converted to JS. This works:

```  
if (actionCodeSettingsMap['android'] != null) {
    webActionCodeSettings.android = auth_interop.AndroidSettings(
      packageName: (actionCodeSettingsMap['android']['packageName'] as String?)?.toJS,
      minimumVersion: (actionCodeSettingsMap['android']['minimumVersion'] as String?)?.toJS,
      installApp: (actionCodeSettingsMap['android']['installApp'] as bool?)?.toJS,
    );
  }

  if (actionCodeSettingsMap['iOS'] != null) {
    webActionCodeSettings.iOS = auth_interop.IosSettings(
      bundleId: (actionCodeSettingsMap['iOS']['bundleId'] as String?)?.toJS,
    );
  }
```

**Comment by sagar1garg** [comment]
@Lyokone pls release an update with this PR asap. A lot of packages are stuck only because of this

**Review by SelaseKay — APPROVED** [review]

**Review by exaby73 — APPROVED** [review]

**Review by russellwheatley — APPROVED** [review]

**Comment by millerf** [comment]
Nice! Thanks for working on it everyone! Will it be deployed on `pub.dev` soon?

**Comment by Kuhlemann** [comment]
It is now deployed.

**Pull request merged**
