### PR TITLE
fix(firebase_ui_auth): Error added in ProfileScreen in firebase_ui_auth 1.4.0

### PR DESCRIPTION
**Pull request by zachary-russell**
## Description

firebase_ui_auth throws an error when building for version 1.4.0.:
`../../.pub-cache/hosted/pub.dev/firebase_ui_auth-1.4.0/lib/src/screens/profile_screen.dart:393:19: Error: Cannot invoke a non-'const' constructor where a const expression is expected. Try using a constructor or factory that is 'const'. const Row( ^^^`

## Related Issues

[Issue](https://github.com/firebase/flutterfire/issues/10954)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ x] All existing and new tests are passing.
- [x ] I updated/added relevant documentation (doc comments with `///`).
- [x ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ x] I read and followed the [Flutter Style Guide].
- [ x] I signed the [CLA].
- [ x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by lesnitsky** [comment]
@zachary-russell 

analyzer fails with your change

```
firebase_ui_auth:
Analyzing ....

   info - lib/src/screens/profile_screen.dart:393:13 - Use 'const' with the constructor to improve performance. Try adding the 'const' keyword to the constructor invocation. - prefer_const_constructors

1 issue found.
```

**Comment by zachary-russell** [comment]
> @zachary-russell analyzer fails with your change
> 
> 
> 
> ```
> 
> firebase_ui_auth:
> 
> Analyzing ....
> 
> 
> 
>    info - lib/src/screens/profile_screen.dart:393:13 - Use 'const' with the constructor to improve performance. Try adding the 'const' keyword to the constructor invocation. - prefer_const_constructors
> 
> 
> 
> 1 issue found.
> 
> ```

I think this issue is what caused the bug in the first place. I'll take a look and see if I can resolve it.

**Comment by zachary-russell** [comment]
@lesnitsky

The prefer_const_constructors warning is ignored in this case because the LoadingIndicator widget used inside the children list of the Row does not have a const constructor. This is due to the fact that LoadingIndicator extends PlatformWidget, which doesn't have a const constructor, making it impossible to have a const constructor for LoadingIndicator. Since we can't make the LoadingIndicator constructor const, we have to ignore the warning for the specific Row constructor. This is an acceptable solution in cases like this, where making the constructor const is not feasible or possible.

Are you aware of another way to solve it I'm definitely willing to give it a stab.

**Comment by russellwheatley** [comment]
hey @zachary-russell, thanks for the PR. Do you mind changing it so the `const` is on children like so: https://github.com/firebase/flutterfire/pull/10963/files. I think that should work but if you could double check it builds on your end that would be great. Thanks 😄

**Comment by zachary-russell** [comment]
Sure, that's what you rejected on the initial[ commit I made](https://github.com/firebase/flutterfire/pull/10957/commits/1f0c13687a5c4911921a23f651477790a19fe866) :)

**Review by russellwheatley — APPROVED** [review]
I think that ought to do it, thanks! 👍

**Review by lesnitsky — APPROVED** [review]

**Comment by bkoznov** [comment]
Is there a timetable/schedule for when this will be released to pub.dev ?

**Pull request merged**
