### PR TITLE
ci: enable `usePubspecOverrides`

### PR DESCRIPTION
**Pull request by blaugold**
## Description

This change switches Melos to use `pubspec_overrides.yaml` file to configure package dependencies for local development.

This has the advantage that as part of bootstrapping `flutter pub get` is executed directly in each package root, ensuring all files generated by the flutter tooling are up-to-date. The relatively large number of changed files is a result of this new behavior.

Use `--no-pub` is no longer necessary because running `flutter pub get` in a package does not negate the effects of `melos bootstrap`.

Bootstrapping this way is also a bit faster.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by blaugold** [comment]
Blocked by https://github.com/invertase/melos/issues/427 so that we can remove the `dependeny_overrides` in the example packages.

**Comment by blaugold** [comment]
@Salakar This PR is ready to review. Tests are failing because of an unrelated issue which has a fix (https://github.com/firebase/flutterfire/pull/10146).

**Comment by blaugold** [comment]
I've started to temporarily track `pubspec_overrides.yaml` files in packages where `intl` needs to be overridden. Once `flutter_localizations` revs `intl` to `0.18.0` those files can be removed from git again.

I've also created an issue for Melos to support this more easily (https://github.com/invertase/melos/issues/439).

**Review by Lyokone — APPROVED** [review]

**Comment by blaugold** [comment]
@Lyokone Could you take another look? I fixed the merge conflicts. The CI failure seems unrelated. It would be great if we could land this before there is another merge conflict.

**Review by Salakar — APPROVED** [review]

**Pull request merged**
