### PR TITLE
fix(firebase_messaging): ensure silent foreground messages for iOS are called via event channel.

### PR DESCRIPTION
**Pull request by russellwheatley**
## Description

see title.

## Related Issues

fixes https://github.com/firebase/flutterfire/issues/8548

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by Ehesp — APPROVED** [review]

**Comment by hugovangalen** [comment]
Silent/data notifications while the app is foregrounded still did not work for me (tested with firebase_messaging 11.4.0).

I was able to trace the problem to the `didReceiveRemoteNotification` and it appears to me that the following line is flawed (line 489 in FLTFirebaseMessagingPlugin.m):

`if (notificationDict[@"aps"] != nil && notificationDict[@"aps"][@"alert"] == nil) {`

As I am logging the contents of the notiticationDict at that point, I see that it does not at all contain an `aps` property. So I wonder whether this is the intended logic there, as it wants to test for the existance of an `alert` property.

`if (notificationDict[@"aps"] == nil || notificationDict[@"aps"][@"alert"] == nil) {`

This seems to fix the issue for me.

**Comment by PapyElGringo** [comment]
11.4.0 doesn't work for me neither

**Comment by hugovangalen** [comment]
Indeed, hence the suggested change in my comment just above yours. https://github.com/firebase/flutterfire/pull/8635#issuecomment-1128724326

Try out that change and if it works, give it a thumbs up ;)

**Comment by PapyElGringo** [comment]
@hugovangalen well I believe it's more of a data model issue than just a condition issue
Because if `notificationDict[@"aps"]` is never populated then your condition is equivalent as `if ( true || true )`

**Comment by russellwheatley** [comment]
@PapyElGringo - How are you sending the message? (i.e. nodeJS admin SDK or REST API, etc)

**Comment by russellwheatley** [comment]
> Silent/data notifications while the app is foregrounded still did not work for me (tested with firebase_messaging 11.4.0 that has this patch merged).
> 
> I was able to trace the problem to the `didReceiveRemoteNotification` and it appears to me that the following line is flawed (line 489 in FLTFirebaseMessagingPlugin.m):
> 
> `if (notificationDict[@"aps"] != nil && notificationDict[@"aps"][@"alert"] == nil) {`
> 
> As I am logging the contents of the notiticationDict at that point, I see that it does not at all contain an `aps` property. So I wonder whether this is the intended logic there, as it wants to test for the presence (or rather, lack) of an `alert` property.
> 
> `if (notificationDict[@"aps"] == nil || notificationDict[@"aps"][@"alert"] == nil) {`
> 
> This seems to fix the issue for me.

@hugovangalen - this won't work because it will fire twice on `onMessage` API if notification + data is present on the message. This code change is strictly firing for data only messages (i.e. when `alert` property is not present on `aps` dictionary).

**Comment by hugovangalen** [comment]
> @hugovangalen - this won't work because it will fire twice on `onMessage` API if notification + data is present on the message. This code change is strictly firing for data only messages (i.e. when `alert` property is not present on `aps` dictionary).

Right okay, I see. I guess I got distracted by the comment above the condition that says "if alert is present, this will be called by the other "Messaging#onMessage" channel handler", which lead me to think that it only dives in this specific routine for data only messages. If the payload has a notification, it goes through another handler `userNotificationCenter` (where the 'aps' property is also missing, and the notification text data is in the "notification" property). I do not observe a double onMessage triggering though with my change.

Anyways, yeah, @PapyElGringo may be right in the 'aps' getting stripped somewhere down the line, but it's stripped before these native handlers get called so that may imply it's a FCM service issue that strips it way? (I also noticed that "to" field gets stripped from the "data" payload, but that is probably another issue altogether.)

**Comment by hugovangalen** [comment]
> @hugovangalen well I believe it's more of a data model issue than just a condition issue Because if `notificationDict[@"aps"]` is never populated then your condition is equivalent as `if ( true || true )`

Yet if it only gets populated when an "alert", or other property is present, then this condition does make sense. 

But you are right, I did some more logging and the 'aps' property is not filled in anywhere when it arrives in the native handlers, so it is indeed a bigger problem that's possibly not fixable by altering the plugin code.

**Comment by hugovangalen** [comment]
> @hugovangalen well I believe it's more of a data model issue than just a condition issue Because if `notificationDict[@"aps"]` is never populated then your condition is equivalent as `if ( true || true )`

I erroneously thought that the notificationDict is what gets delivered by the operating system to the app, yesterday I overlooked the call to [FLTFirebaseMessagingPlugin remoteMessageUserInfoToDict:userInfo] which is where the problem arises, 'aps' is present in userInfo, but not in the resulting dictionary.

In fact, in remoteMessageUserInfoToDict, this is happening:

```
    // build data dict from remaining keys but skip keys that shouldn't be included in data
    if ([key isEqualToString:@"aps"] || [key hasPrefix:@"gcm."] || [key hasPrefix:@"google."]) {
      continue;
    }
```

It seems that the 'aps' *intensionally* gets stripped. It kinda does make sense to strip it, as it is operating system specific data that doesn't need to end up in the Flutter app, but it does break the condition back in didReceiveRemoteNotification.

@russellwheatley I suspect that in stead of notificationDict, the userInfo should be tested in line 489:
`if (userInfo[@"aps"] != nil && userInfo[@"aps"][@"alert"] == nil) {`

**Comment by PapyElGringo** [comment]
@russellwheatley I use `sendMulticast` API

**Comment by hugovangalen** [comment]
@PapyElGringo Could you please cconfirm that for you, when you dump the `userInfo` dictionary, that *does* contain the 'aps' property?

**Comment by PapyElGringo** [comment]
My background notifications are blocked because of quotas and priority

**Comment by russellwheatley** [comment]
> > @hugovangalen well I believe it's more of a data model issue than just a condition issue Because if `notificationDict[@"aps"]` is never populated then your condition is equivalent as `if ( true || true )`
> 
> I erroneously thought that the notificationDict is what gets delivered by the operating system to the app, yesterday I overlooked the call to [FLTFirebaseMessagingPlugin remoteMessageUserInfoToDict:userInfo] which is where the problem arises, 'aps' is present in userInfo, but not in the resulting dictionary.
> 
> In fact, in remoteMessageUserInfoToDict, this is happening:
> 
> ```
>     // build data dict from remaining keys but skip keys that shouldn't be included in data
>     if ([key isEqualToString:@"aps"] || [key hasPrefix:@"gcm."] || [key hasPrefix:@"google."]) {
>       continue;
>     }
> ```
> 
> It seems that the 'aps' _intensionally_ gets stripped. It kinda does make sense to strip it, as it is operating system specific data that doesn't need to end up in the Flutter app, but it does break the condition back in didReceiveRemoteNotification.
> 
> @russellwheatley I suspect that in stead of notificationDict, the userInfo should be tested in line 489: `if (userInfo[@"aps"] != nil && userInfo[@"aps"][@"alert"] == nil) {`

@hugovangalen thanks for the investigation. I will double check and get back to you on this 🙏

**Pull request merged**
