### PR TITLE
fix(firestore, windows): fix compilation issue on Windows

### LINKED ISSUE #12359: 🐛 [cloud_firestore] [windows] error C2440: '<function-style-cast>' after updating to flutter 3.19
## Bug report

**Describe the bug**
after updating to flutter 3.19 is started getting the following error when trying to build for windows

```
/IF:\Repos\laywer_bro\windows\flutter\ephemeral\cpp_client_wrapper\include /Zi /nologo /W4 /WX /diagnostics:column /Od /Ob0 /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D _HAS_EXCEPTIONS=0 /D _DEBUG /D
FLUTTER_PLUGIN_IMPL /D INTERNAL_EXPERIMENTAL=1 /D UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17
/Fo"cloud_firestore_plugin.dir\Debug\\" /Fd"F:\Repos\laywer_bro\build\windows\x64\plugins\cloud_firestore\Debug\cloud_firestore_plugin.pdb" /external:W0 /Gd /TP /wd4100 /errorReport:queue  /external:I
"F:/Repos/laywer_bro/build/windows/x64/extracted/firebase_cpp_sdk_windows/include" F:\Repos\laywer_bro\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin_c_api.cpp
F:\Repos\laywer_bro\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin.cpp
F:\Repos\laywer_bro\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\messages.g.cpp F:\Repos\laywer_bro\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\firestore_codec.cpp      
[  +30 ms]   cloud_firestore_plugin_c_api.cpp
[ +739 ms]   cloud_firestore_plugin.cpp
[ +748 ms] F:\Repos\laywer_bro\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin.cpp(1446,43): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to'cloud_firestore_windows::AggregateQueryResponse' [F:\Repos\laywer_bro\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
[   +2 ms] F:\Repos\laywer_bro\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin.cpp(1446,43): message :
'cloud_firestore_windows::AggregateQueryResponse::AggregateQueryResponse': function does not take 2 arguments [F:\Repos\laywer_bro\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
[        ] F:\Repos\laywer_bro\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin.cpp(1446,43): message : while trying to match the argument list
'(cloud_firestore_windows::AggregateType, double)' [F:\Repos\laywer_bro\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
[        ] F:\Repos\laywer_bro\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin.cpp(1445,66): error C2512: 'flutter::CustomEncodableValue': no appropriate default
constructor available [F:\Repos\laywer_bro\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
[   +2 ms] F:\Repos\laywer_bro\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin.cpp(1445,66): message : 'flutter::CustomEncodableValue::CustomEncodableValue': no appropriatedefault constructor available [F:\Repos\laywer_bro\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
[        ] F:\Repos\laywer_bro\windows\flutter\ephemeral\.plugin_symlinks\cloud_firestore\windows\cloud_firestore_plugin.cpp(1445,66): message : while trying to match the argument list '()'
[F:\Repos\laywer_bro\build\windows\x64\plugins\cloud_firestore\cloud_firestore_plugin.vcxproj]
```

image

### Steps to reproduce

1. make sure you're on flutter 3.19
2. use cloud firestore in any project
3. perform `flutter run`

### Expected behavior

it should build with no issues

### Sample project

N/A 
i even tested on the counter app

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.19045.4046], locale en-GB)
    • Flutter version 3.19.0 on channel stable at C:\Users\Nour\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (7 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at F:\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = F:\Android
    • Java binary at: F:\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.7.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.7.34221.43
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2023.1)
    • Android Studio at F:\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.86.2)
    • VS Code at C:\Users\Nour\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4046]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.185
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.128

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 3.3.0
Flutter SDK 3.19.0
laywer_bro 1.0.0+1

dependencies:
- bitsdojo_window 0.1.6 [flutter bitsdojo_window_platform_interface bitsdojo_window_windows bitsdojo_window_macos bitsdojo_window_linux]
- cloud_firestore 4.15.5 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.6
- flex_color_scheme 7.3.1 [flex_seed_scheme flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- go_router 13.2.0 [collection flutter flutter_web_plugins logging meta]
- google_fonts 6.1.0 [flutter http path_provider crypto]
- queen_validators 1.0.1 [email_validator flutter]
- signals 4.2.3 [flutter signals_core signals_flutter]
- signals_flutter 4.2.3 [flutter signals_core]
- supabase_flutter 2.3.3 [app_links async crypto flutter http meta supabase url_launcher path_provider shared_preferences]

dev dependencies:
- build_runner 2.4.8 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- go_router_builder 2.4.1 [analyzer async build build_config collection meta path source_gen source_helper]

transitive dependencies:
- _fe_analyzer_shared 67.0.0 [meta]
- _flutterfire_internals 1.3.22 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.4.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- app_links 3.5.0 [flutter plugin_platform_interface flutter_web_plugins gtk]
- args 2.4.2
- async 2.11.0 [collection meta]
- bitsdojo_window_linux 0.1.4 [flutter bitsdojo_window_platform_interface ffi]
- bitsdojo_window_macos 0.1.4 [flutter bitsdojo_window_platform_interface ffi]
- bitsdojo_window_platform_interface 0.1.2 [flutter meta plugin_platform_interface]
- bitsdojo_window_windows 0.1.6 [flutter bitsdojo_window_platform_interface win32 ffi]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.0 [built_collection collection fixnum meta]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 6.1.6 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.10.5 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- convert 3.1.1 [typed_data]
- crypto 3.0.3 [typed_data]
- dart_style 2.3.4 [analyzer args collection path pub_semver source_span]
- email_validator 2.1.17
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 7.0.0 [meta path]
- firebase_core 2.25.4 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.11.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- fixnum 1.1.0
- flex_seed_scheme 1.4.0 [collection flutter meta]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 3.2.0 [async path]
- functions_client 2.0.0 [http yet_another_json_isolate]
- glob 2.1.2 [async collection file path string_scanner]
- gotrue 2.5.0 [collection crypto http jwt_decode rxdart meta]
- graphs 2.3.1 [collection]
- gtk 2.1.0 [ffi flutter meta]
- http 1.2.0 [async http_parser meta web]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- json_annotation 4.8.1 [meta]
- jwt_decode 0.3.1
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 2.1.1
- logging 1.2.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- mime 1.0.5
- package_config 2.1.0 [path]
- path 1.9.0
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- postgrest 2.1.0 [http yet_another_json_isolate meta]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- realtime_client 2.0.0 [collection http meta web_socket_channel]
- retry 3.1.2
- rxdart 0.27.7
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.5 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- signals_core 4.2.1
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- storage_client 2.0.1 [http http_parser mime retry meta]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- supabase 2.0.7 [functions_client gotrue http postgrest realtime_client storage_client rxdart yet_another_json_isolate]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- url_launcher 6.2.4 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.2.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- vm_service 13.0.0
- watcher 1.1.0 [async path]
- web 0.3.0
- web_socket_channel 2.4.0 [async crypto stream_channel]
- win32 5.2.0 [ffi]
- xdg_directories 1.0.4 [meta path]
- yaml 3.1.2 [collection source_span string_scanner]
- yet_another_json_isolate 2.0.0 [async]

```

</details>

---

### PR DESCRIPTION
**Pull request by Lyokone**
## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

closes #12359 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by SPiercer** [comment]
Thanks it works, i tried your changes locally and worked on the example app testing on my app now

**Review by SPiercer — APPROVED** [review]
Changes Worked on my device and in my app LGTM

**Review by SPiercer — APPROVED** [review]

**Comment by SPiercer** [comment]
@russellwheatley or @exaby73 can someone approve and merge those please we're severely blocked and we need to have a release soon

**Review by mesalih — APPROVED** [review]
I've test it locally on my device and does resolves the issue.

**Review by PolaraPrince — COMMENTED** [review]
This change has helped me, so I am grateful.

**Comment by BirjuVachhani** [comment]
This fixes the issue on windows. I can confirm.

**Review by russellwheatley — APPROVED** [review]

**Comment by SPiercer** [comment]
@Lyokone How long usually PR stay until it gets merged?

**Comment by SPiercer** [comment]
@russellwheatley that's what I'm saying, it's not merged to master yet.

or do you mean depend on the fix branch?

**Comment by Aravind556** [comment]
Issue fixed.Thank You

**Pull request merged**
