### PR TITLE
feat(cloud_firestore_odm): add support for specifying class name prefix

### PR DESCRIPTION
**Pull request by Rexios80**
## Description

Allows developers to specify the name prefix used for generated classes. This allows for reusing the same data class in multiple sub collections on the same parent collection.

## Related Issues

#9452

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by rrousselGit** [comment]
I think another important thing to do for #9452 is to throw an error if the same Model is used on multiple collections. Could you add that?

**Comment by rrousselGit** [comment]
Outside of error handling, LGTM

**Comment by Rexios80** [comment]
> I think another important thing to do for #9452 is to throw an error if the same Model is used on multiple collections. Could you add that?

I'm not sure what you mean. Do you mean throw an exception if the same model is used on multiple root collections?

**Comment by rrousselGit** [comment]
Yes. If multiple `@Collection` annotation uses the same generics, it should throw (root or not)

**Comment by rrousselGit** [comment]
LGTM thanks!

**Review by rrousselGit — APPROVED** [review]

**Review by Lyokone — APPROVED** [review]

**Pull request merged**
