### PR TITLE
chore: add license header for missing files

### PR DESCRIPTION
**Pull request by nilsreichardt**
## Description

I'm going to split #9702 into two PRs:
1. adding the license header for all missing files (a big PR with many file changes)
2. adding the GitHub Action check for the license header with instructions on adding the license with one command (see https://github.com/firebase/flutterfire/pull/9704)

I used this command (in the next PR I'm going to add this as a `melos` command):
```sh
addlicense -f header_template.txt --ignore "**/*.yml" --ignore "**/*.yaml" --ignore "**/*.xml" --ignore "**/*.g.dart" --ignore "**/*.sh" --ignore "**/*.html" --ignore "**/*.js" --ignore "**/*.ts" --ignore "**/*.g.h" --ignore "**/*.g.m" --ignore "**/*.rb" --ignore "**/Runner/AppDelegate.swift" --ignore "**/Runner/MainFlutterWindow.swift" --ignore "**/Runner/Runner-Bridging-Header.h" --ignore "**/Runner/AppDelegate.h" --ignore "**/Runner/AppDelegate.m" --ignore "**/Runner/main.m" --ignore "**/MainActivity.kt" --ignore "**/MainActivity.java" --ignore "**/FlutterMultiDexApplication.java" --ignore **/GeneratedPluginRegistrant.swift .
```

with this in my `header_template.txt`
```txt
Copyright {{.Year}}, the Chromium project authors.  Please see the AUTHORS file
for details. All rights reserved. Use of this source code is governed by a
BSD-style license that can be found in the LICENSE file.
```

## Related Issues

Part of #9702 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by nilsreichardt** [comment]
I have added the missing headers with [`addlicense`](https://github.com/google/addlicense).

On which files do we want to add the license headers? I just used the default settings of `addlicense` but we could use the `--ignore` parameter.

**Comment by nilsreichardt** [comment]
> On which files do we want to add the license headers? I just used the default settings of addlicense but we could use the --ignore parameter.

Discussed in Slack: We are going to use these ignore flags: `--ignore "**/*.yml" --ignore "**/*.yaml" --ignore "**/*.xml" --ignore "**/*.g.dart" --ignore "**/*.sh" --ignore "**/*.html" --ignore "**/*.js" --ignore "**/*.ts" --ignore "**/*.g.h" --ignore "**/*.g.m" --ignore "**/*.rb" --ignore "**/Runner/AppDelegate.swift" --ignore "**/Runner/MainFlutterWindow.swift" --ignore "**/Runner/Runner-Bridging-Header.h" --ignore "**/Runner/AppDelegate.h" --ignore "**/Runner/AppDelegate.m" --ignore "**/Runner/main.m" --ignore "**/MainActivity.kt" --ignore "**/MainActivity.java" --ignore "**/FlutterMultiDexApplication.java" --ignore **/GeneratedPluginRegistrant.swift`

**Comment by nilsreichardt** [comment]
This is the second part: https://github.com/firebase/flutterfire/pull/9704

**Review by Salakar — APPROVED** [review]

**Review by Lyokone — APPROVED** [review]
LGTM, there are some conflicts, if you can fix them, I'll try to get that merged quickly :)

**Comment by nilsreichardt** [comment]
@Lyokone Thanks for the review :) I solved the conflicts 👍

**Pull request merged**
