### PR TITLE
fix(auth, android): fix crash on Android where detaching from engine was not properly resetting the Pigeon handler

### PR DESCRIPTION
**Pull request by Lyokone**
## Description

See title 

## Related Issues

Fixes https://github.com/firebase/flutterfire/issues/9210

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by russellwheatley — APPROVED** [review]

**Comment by alectogeek** [comment]
Any updates here? 
It's a kinda urgent fix :D

**Review by Ehesp — APPROVED** [review]

**Comment by timobaehr** [comment]
What is the version for the fix?

**Comment by alectogeek** [comment]
> What is the version for the fix?

It is not published yet. The will include it to 3.5.2, I guess

**Comment by timobaehr** [comment]
Does anyone know the right version mix to downgrade? 3.4.2 saying for Android build:
```
Unexpected element  (URI:"", lokal:"base-extension").
../../../.pub-cache/hosted/pub.dartlang.org/firebase_auth-3.4.2/lib/src/recaptcha_verifier.dart:57:27: Error: Required named parameter 'auth' must be provided.
      _factory.delegateFor(
```

In my `pubspec.yaml`: `firebase_auth: '<=3.4.2'`. Same for `3.4.1` and `3.3.20`.

**Comment by bhumkong** [comment]
@timobaehr you can pin these versions:
```
dependencies:
  firebase_auth: 3.4.2
dependency_overrides:
  firebase_auth_platform_interface: 6.3.2
```

**Comment by skobak** [comment]
Seems like the  firebase_auth: ^3.6.1 is fixing that issue for me.   (3.6.0 contain the fix itself)
will keep testing...

**Comment by nilsreichardt** [comment]
> What is the version for the fix?

The fix is published in version `3.6.0`. You can see the changelog of this version here: https://pub.dev/packages/firebase_auth/changelog#360

**Pull request merged**
