### PR TITLE
Update pubspec.yaml

### PR DESCRIPTION
**Pull request by ZiyadF296**
Bumped intl package version.

## Description

Increased `intl` package version from ^0.17.0 to ^0.18.1.

## Related Issues

Incompatible to be added in projects that rely on `intl ^0.18.1`

## Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by thassio-vinicius — APPROVED** [review]

**Comment by StevenSnary** [comment]
Looks like the PR title should include a prefix - I suggest "refactor: Update pubspec.yaml"
@ZiyadF296

**Comment by ryosoul** [comment]
Forgive me if I'm wrong, but flutter_localizations have a restrict version specification for intl 0.18.0, setting this to 0.18.1 don't break flutter pub get?

**Comment by BirjuVachhani** [comment]
What's the status on this? This is a required change for this work with Flutter v3.10.0. I literally can't upgrade because of this!

**Review by ekasetiawans — APPROVED** [review]

**Comment by ekasetiawans** [comment]
@ZiyadF296 please update the PR title

**Pull request closed without merging**
