### PR TITLE
fix(database, web): fix broken exception handling on streams

### PR DESCRIPTION
**Pull request by russellwheatley**
## Description

- fixed incorrect web stream handling by passing in raw exception for exception parsing.
- wrote a couple of tests to prove fix.

## Related Issues

fixes https://github.com/firebase/flutterfire/issues/12642

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by TarekkMA — APPROVED** [review]

**Review by Lyokone — APPROVED** [review]

**Comment by guvenacar** [comment]
Hello @russellwheatley, will the update be included in the new version? When will the new version be released? I can't use realtime database in my project still. Thanks.

**Comment by russellwheatley** [comment]
@guvenacar - Released in latest version 👍

**Comment by guvenacar** [comment]
@russellwheatley, I keep getting the same error after the last update?!

**Comment by russellwheatley** [comment]
@guvenacar - some other fixes were needed: https://github.com/firebase/flutterfire/pull/12706
will be out in next release 👍

**Comment by guvenacar** [comment]
after update still dont work :(

**Pull request merged**
