### PR TITLE
docs: Redirect from firebase.flutter.dev to firebase.google.com

### PR DESCRIPTION
**Pull request by kevinthecheung**
## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Ehesp** [comment]
The redirects look good, however I've got a couple of questions:

1. The firebase.json still has a `public` property pointing to `build`, which no longer exists.
2. Can we remove the rewrites given there is no longer an index page to rewrite to - the redirects should handle this(?)

Also, I've not actually tried deploying "nothing" to Firebase Hosting - will we need to add a dummy index.html file or will it deploy with just redirects?

**Comment by Ehesp** [comment]
Just pulled it and tried to deploy to another project - had to remove the build and rewrites so all good now.

**Review by Ehesp — APPROVED** [review]

**Review by russellwheatley — APPROVED** [review]
LGTM

**Comment by nilsreichardt** [comment]
Is the documentation now still open source? If yes, is there a repository?

**Comment by kevinthecheung** [comment]
> Is the documentation now still open source? If yes, is there a repository?

Yes! The Flutter docs on firebase.google.com are now in docs/ and they are open source.

**Comment by nilsreichardt** [comment]
Ah, nice 👍 Thanks, @kevinthecheung

**Pull request merged**
