### PR TITLE
feat(flutterfire_ui): added getter 'size' to query_builder

### PR DESCRIPTION
**Pull request by al4nnw**
## Description

Adds hability to get the size of a query within a snapshot.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by lesnitsky** [comment]
@al4nnw could you please run `melos run format`?

**Comment by al4nnw** [comment]
Tried running the command and it crashed before completing, but I noticed that the file I touched (query_builder.dart) had being correctly formated and I managed to stage and commit it. 

I could try running it again if it is necessary.

**Comment by Bluewater1020** [comment]
infringement of copyright 48 cfr 102 uk 48 cfr 101 japan farmer president international canabis project intellectual property meaning bussines requirements unlawful intrest in a public contract is a violation 2921.15 ohio merchabilty and fitness is a stand alone policy

**Comment by lesnitsky** [comment]
Please open this PR in [firebase/FirebaseUI-Flutter](https://github.com/firebase/FirebaseUI-Flutter)

**Pull request closed without merging**
