### PR TITLE
feat(*web):  switch to latest v9 Firebase JS SDK (compat)

### PR DESCRIPTION
**Pull request by russellwheatley**
## Description

Explore the possibility of using web v9 compat SDKs.

## Related Issues

closes https://github.com/FirebaseExtended/flutterfire/issues/7041

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Salakar** [comment]
Current known issues:

 - Auth Error messages have changed, are now prefixed with `Firebase: `
 - Auth updatePhotoURL no longer accepts null - how do you now remove a photo from a user profile if this is still possible?
 - Auth updateDisplayName no longer accepts null - how do you now remove a display name from a user profile if this is still possible?

**Comment by Ehesp** [comment]
FYI the v9 SDKs do infact accept null, or should:

image

I can do some digging and see if it's an SDK issue.

**Comment by Salakar** [comment]
> FYI the v9 SDKs do infact accept null, or should:
> 
> image
> 
> I can do some digging and see if it's an SDK issue.

@Ehesp could it be the compat layer maybe?

**Comment by Ehesp** [comment]
Confirmed v9 SDK itself allows null to be set, will check the compat layer.

**Comment by Ehesp** [comment]
And on 9.4.0 compat it also works fine in the browser. Hmm.

**Comment by Ehesp** [comment]
@googlebot I consent.

**Comment by Ehesp** [comment]
The errors come through with additional space/periods after the message too:

```
Firebase: The email address is badly formatted. (auth/invalid-email).
```

**Comment by Ehesp** [comment]
Tried all sorts - cannot get `null` values to be accepted. Going to have to hold off merging this one.

**Comment by Salakar** [comment]
@russellwheatley @Ehesp - it looks like `SDK_VERSION` used in tests and internally is now gone, we should update internals and tests to remove usages to get this PR working

**Comment by russellwheatley** [comment]
Still keeping this as blocked as latest compat versions do not appear to work. Firebase installations-compat script is non-existent. But the e2e tests simply hang as well which might be a result of no installations module. Not sure it's worth pursuing this if we're doing a rewrite of the webs side of things for web v9 integration.

**Comment by ChristianEdwardPadilla** [comment]
@russellwheatley Has a decision been made on whether to go forward with this upgrade or to wait for a web rewrite? Also, where can I follow along with that kind of discussion? An app in google would like to see this JS dep upgrade happen.

**Pull request closed without merging**
