### PR TITLE
fix(storage, windows): Reference.putData does not work as expected on Windows

### PR DESCRIPTION
**Pull request by espresso3389**
## Description

Reference.putData writes some garbage on Firebase Storage.

The reason behind the issue is that:

- FirebaseStoragePlugin::ReferencePutData/FirebaseStoragePlugin::ReferencePutString passes wrong byte sequence/size to PutDataStreamHandler
- PutDataStreamHandler does not keep the actual data but just a dangling pointer

## Related Issues
 
-

## Checklist

For Windows, there seems almost no tests. How should I start testing with the current situation???

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by russellwheatley** [comment]
@espresso3389 - Thank you for this. Could you merge this with master and we can look to to get this merged?

We don't currently have integration test for Windows storage as their is no emulator available on the C++ SDK. We make it clear on the [README](https://github.com/firebase/flutterfire) windows is not production ready.

**Comment by espresso3389** [comment]
@russellwheatley I've merged the latest master commit. Could you take a look?

**Comment by russellwheatley** [comment]
Hey @espresso3389 - there's quite a few things I found not working as intended on Storage windows and I'm going to be fixing them and adding e2e tests 🤞. It is work in progress but here is my PR if you want to track progress: https://github.com/firebase/flutterfire/pull/12723

**Comment by russellwheatley** [comment]
@espresso3389 - This has been merged now, should be out in the next release: https://github.com/firebase/flutterfire/pull/12723

**Pull request closed without merging**
