### PR TITLE
test: migrate all packages from Flutter driver to integration tests

### LINKED ISSUE #8909: Migrate e2e tests from Flutter Driver to `integration_test` package
## Description
The `integration_test` is the new way to write e2e tests. Therefore, we should migrate all packages from Flutter Driver to `integration_test`.

We will split the migration into multiple pull requests. All pull requests will be merged into the [`migrate-to-integration-tests`](https://github.com/firebase/flutterfire/tree/migrate-to-integration-tests) branch.

We should also check at the end if the CI is flaky by running like 100 times the same job.

### PR DESCRIPTION
**Pull request by nilsreichardt**
## Description

The `integration_test` package is the new way to write e2e tests. Therefore, this PR migrates the tests from driver tests to integration tests.

As side effect, we see that the Android CI e2e tests pipeline is way more stable.

### ToDos:

- [ ] Migrate `cloud_firestore`
- [x] Migrate `cloud_functions`
- [x] Migrate `firebase_analytics`
- [x] Migrate `firebase_app_installations`
- [x] Migrate `firebase_auth`
- [x] Migrate `firebase_core`
- [x] Migrate `firebase_crashlytics`
- [x] Migrate `firebase_database`
- [x] Migrate `firebase_dynamic_links`
- [x] Migrate `firebase_in_app_messaging`
- [ ] Migrate `firebase_ml_model_downloader`
- [ ] Migrate `firebase_remote_config`
- [x] Migrate `firebase_messaging`
- [ ] Migrate `firebase_storage`
- [ ] Migrate `firebase_firestore_odm`
- [ ] Migrate `firebase_performance`
- [ ] Delete driver tests (test_driver/ folder)
- [ ] Remove `drive` as dependency
- [ ] Mark `drive` dependency on pub.dev as discontinued?
- [ ] Check if CI is flaky (run CI 50 times)
- [ ] Update docs on how to run integration tests

## Related Issues

Closes #8909

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by cedvdb** [comment]
finally

**Comment by russellwheatley** [comment]
Hey @nilsreichardt, I've fixed the merge conflicts for you. Let me know if you need any further assistance 🙏

**Comment by nilsreichardt** [comment]
Thanks, @russellwheatley 🙏

**Comment by nilsreichardt** [comment]
Hey @russellwheatley, could you again merge the `master` into this branch?

**Comment by russellwheatley** [comment]
Done, @nilsreichardt 😄

**Comment by nilsreichardt** [comment]
I started from scratch and opened a new PR where I migrated all packages in one PR: https://github.com/firebase/flutterfire/pull/9649

**Pull request closed without merging**
