### PR TITLE
fix(firebase_auth): added supporting rawNonce for OAuth credential on Windows platform

### PR DESCRIPTION
**Pull request by JekaNS**
## Description

Added support for the rawNonce field in credential builder on the Windows platform.

Since there is no implementation of AppleAuthProvider on Windows platform, I am trying to use OAuthProvider. This works on MacOS, but on Windows I couldn't pass an idToken with a rawNonce and no accessToken to the credential builder. And signInWithCredentials threw an exception.

With this PR if rawNonce is provided then will be used overloaded credential builder firebase::auth::OAuthProvider::GetCredential that accept rawNonce argument.

Example of use:

```dart
    final credential = OAuthProvider("apple.com").credential(idToken: webAuthRes.idToken, rawNonce: webAuthRes.nonce);
    FirebaseAuth.instance.signInWithCredential(credential);
```

## Related Issues

No existing issues found ((

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Lyokone** [comment]
Hello @JekaNS thanks a lot for this feature, it looks great. I'll do a couple of manual tests first but it should be fine

**Comment by Lyokone** [comment]
Can you just check the formatting of the files?

**Comment by JekaNS** [comment]
Hi @Lyokone,
Sure. Formating fixed.

**Review by Lyokone — APPROVED** [review]

**Review by exaby73 — APPROVED** [review]

**Comment by Lyokone** [comment]
Thanks for the contribution!

**Pull request merged**
