### PR TITLE
fix(flutterfire_ui): migrate flutterfire_ui to flutter v3

### PR DESCRIPTION
**Pull request by aadarshadhakalg**
## Description

This PR migrates the flutterfire_ui package to be compatible with Flutter version 3.

## Related Issues

#8948 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by Lyokone — APPROVED** [review]

**Review by nilsreichardt — COMMENTED** [review]
I already fixed this in https://github.com/firebase/flutterfire/pull/8651. But it got reverted in #8713 to support Flutter versions blow 3.0.

**Comment by nilsreichardt** [comment]
> Maybe we should leave some comments in the code then 🤔

Yes, I think this PR already shows that this is not clear. We should also decide when we drop the support for the Flutter versions because until we have like now every user with Flutter >= 3 get this the following warning when running the tests or build the app:

```
ib/src/auth/screens/email_verification_screen.dart:97:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which
excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
 ('../../../../../fvm/versions/3.0.2/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback(_sendEmailVerification);
```

**Comment by aadarshadhakalg** [comment]
What can I do next? Is there any way we could find the version of Flutter that is being used?

**Comment by aadarshadhakalg** [comment]
@lesnitsky 
I followed the documentation from here: https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0
Hopefully, this will work.
I will check it once and let you know.

**Review by lesnitsky — APPROVED** [review]

**Pull request merged**
