### PR TITLE
test(firebase_messaging): migrate to `integration_test` package

### PR DESCRIPTION
**Pull request by nilsreichardt**
## Description

Migrates the Flutter Driver tests to Flutter Integration tests. I just copied the Flutter Driver. So I have not changed any test.  

## Related Issues

Part of #6829 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by nilsreichardt** [comment]
I think I need to fix this broken CI

**Comment by russellwheatley** [comment]
@nilsreichardt The android CI is pretty flaky at the moment. But I've noticed that these integration tests are way less flaky than the previous implementation using `drive`.

**Comment by nilsreichardt** [comment]
@russellwheatley Yeah, I have also see feeling. I'm not sure if it's worth to invest more time in #9076 🤔 I have also planned to make a stability test when I migrated every package (similar I need with the `all_plugins` jobs)

**Comment by russellwheatley** [comment]
@nilsreichardt yes, I'm going to leave that PR because I think this should really improve the e2e tests 😄

**Comment by nilsreichardt** [comment]
@russellwheatley I'm going to do it this week :)

**Pull request merged**
