### PR TITLE
fix(database): Fix convertFirebaseDatabaseException failing if no message is provided

### PR DESCRIPTION
**Pull request by smith897**
## Description

convertFirebaseDatabaseException throws a null exception if the exception does not contain a message. This fixes the issue by allowing the retrieved message to be null.

This null exception is caught before it reaches the caller, so the caller is never notified their subscription is no longer active. If there's a .onError callback attached, it is never called.

## Related Issues

https://github.com/firebase/flutterfire/issues/10969
This issue describes the problem, but was closed due to inactivity.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by smith897** [comment]
@russellwheatley  Sure, I was able to recreate it by just calling this from the root of my application
`FirebaseDatabase.instance.ref("test").onValue.listen((event) {
  print("New event: ${event.toString()}");
});`

I created the "test" entry through the firebase console. Once I was listening, I went into the console and changed the "reads" rule in the rules to false.

Basically, it can be recreated by listening to something, and then revoking access to it.

**Comment by smith897** [comment]
I guess I should also mention, as this happens in convertFirebaseDatabaseException, it must be done in Flutter web.

**Comment by russellwheatley** [comment]
I followed up on this and I was able to recreate. It seems odd that no message was provided so I checked on a pure web implementation and it seems correct that a message is not provided:
Screenshot 2023-08-31 at 16 13 04

**Comment by smith897** [comment]
@russellwheatley Thank you! I'm surprised that Android end to end tests are preventing a merge, since the only change was in the web implementation. Do you know if that's something I need to look into?

**Comment by russellwheatley** [comment]
@smith897 - the android CI is somewhat flaky, don't worry about that. I'll ensure it goes green 👍

**Review by russellwheatley — APPROVED** [review]

**Comment by exaby73** [comment]
@smith897 Can you add a test for this? I believe this is only needed for the web platform. You can update a `ref` in a query to one that would through a permission denied error and check if the exception is generated correctly. Other than this, it LGTM

**Comment by russellwheatley** [comment]
> @smith897 Can you add a test for this? I believe this is only needed for the web platform. You can update a `ref` in a query to one that would through a permission denied error and check if the exception is generated correctly. Other than this, it LGTM

Hey @smith897 - are you able to write an e2e test as mentioned above? Thanks

**Pull request closed without merging**
