### PR TITLE
feat(core): support TrustedType

### LINKED ISSUE #10311: 🐛 [firebase_core_web] TrustedType violations
## Bug report

**Describe the bug**
Google Flutter web apps using Firebase plugins that rely on firebase_core_web are receiving browser error reports through the [TrustedTypes](https://web.dev/trusted-types/) browser APIs. Specifically, the script injection code in [_injectSrcScript](https://github.com/firebase/flutterfire/blob/master/packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart) is not adhering to the standards and is causing errors to be logged.

### Steps to reproduce

Run a Flutter Web app on a browser with TrustedType API support, or polyfill present.

### Expected behavior

Script manipulation should not trigger TrustedType violations.

### Example migration

Some script-manipulation code in the Flutter framework has already been migrated to satisfy the TrustedType checks. Here are two examples:

https://github.com/flutter/flutter/pull/112969/files

https://github.com/flutter/packages/blob/main/packages/google_identity_services_web/lib/src/js_loader.dart#L28-L44

### PR DESCRIPTION
**Pull request by Lyokone**
## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

closes #10311 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by Ehesp — APPROVED** [review]
LGTM

**Review by russellwheatley — APPROVED** [review]

**Comment by Lyokone** [comment]
@kevinthecheung I've added some documentation on Trusted Types. Let me know if you think this documentation should be placed somewhere else.

**Comment by Lyokone** [comment]
I'll merge it for release, let me know if I should open another PR for moving the documentation.

**Comment by adar2378** [comment]
Guys is this something related? 
https://github.com/firebase/flutterfire/issues/10474

**Pull request merged**
