### PR TITLE
docs(firebase_messaging): Update example app & documentation for initializing Firebase app from top-level.

### PR DESCRIPTION
**Pull request by russellwheatley**
## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

fixes https://github.com/FirebaseExtended/flutterfire/issues/6087

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by Lyokone — APPROVED** [review]

**Comment by russellwheatley** [comment]
Decided to solve this at the root. I believe there are too many connections/writes at the same time to the SQL instance hence the error. Possibly need to cache Firebase instance if initializing app from separate isolate.

**Comment by russellwheatley** [comment]
Closing as the issue appears to be resolved.

**Comment by deepak786** [comment]
@russellwheatley Is it resolved from the firebase package itself?

**Comment by russellwheatley** [comment]
@deepak786 The issue is closed so I presumed it was resolved. Are you still experiencing the issue?

**Comment by deepak786** [comment]
@russellwheatley we are using the approach defined in this PR. So I want to know if we should continue with that or not.

**Comment by russellwheatley** [comment]
@deepak786 I'm not sure, I presumed the lack of responses to the issue, and that it was closed meant it had been resolved at the level of the SDK. I think I'd prefer to reopen the issue if it is still a problem.

**Comment by Mayb3Nots** [comment]
> @deepak786 I'm not sure, I presumed the lack of responses to the issue, and that it was closed meant it had been resolved at the level of the SDK. I think I'd prefer to reopen the issue if it is still a problem.

Hi @russellwheatley, Im getting same error message in Crashnalytic today. I saw that you mentioned fixing it at the root where the SQL instance seemed to be overwhelm, is that still planned or do I have to implement the fix suggested by this PR?

**Comment by giorgio79** [comment]
Hope making initapp a global will solve the originating issue:
https://github.com/firebase/flutterfire/issues/6087

I reworked my app based on the Firebase Messaging Flutter example app, and with two initilizeApp calls I started seeing the referenced github issue...

**Comment by Lyokone** [comment]
Closing this since it's not relevant anymore.

**Pull request closed without merging**
