### PR TITLE
fix: missing dependency

### PR DESCRIPTION
**Pull request by jarrodcolburn**
## Description

Missing dependency when trying to run example

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Lyokone** [comment]
Did you run `melos bs` before trying to run the example?

**Comment by jarrodcolburn** [comment]
From @Lyokone 
> Did you run `melos bs` before trying to run the example?

No, I have to plead ignorance as... I didn't even know what `melos` was until reading your comment just now.

Perhaps my suggested PR may be the wrong fix, but I still think a fix may be warranted. May I suggest...

Include instructions to `melos bs` in the example's README?

**Comment by russellwheatley** [comment]
@jarrodcolburn - if you wish, you could add a small section [here](https://github.com/firebase/flutterfire/blob/master/packages/cloud_firestore_odm/README.md) that illustrates `melos bs` has to be called in order to link packages before running example app (which I believe is the issue, but I'd ask you to double check first if you'd be so kind). Thanks.

**Comment by russellwheatley** [comment]
Closing out due to inactivity and suspected incorrect setup.

**Pull request closed without merging**
