### PR TITLE
fix(ui): set the default variant of LoadingButton to outlined (#8443)

### LINKED ISSUE #8443: [flutterfire_ui] Email form's Loading button is now TextButton by default and can not be changed
## Bug report

**Describe the bug**
[This](https://github.com/firebase/flutterfire/pull/8333) pull request added the ButtonVariant property to the LoadingButton, but when using composite UI elements like EmailForm, the default ButtonVariant (ButtonVariant.text) can not be overridden to use the previously used Outlined button version. This leaves the UI element without being stylable, especially because now both the LoadingButton and the ForgotPasswordButton are TextButtons, thus can only be styled together. 

### Steps to reproduce

1. Check the EmailFormWidget.

### Expected behavior

Composite UI elements using LoadingButton-s should be configurable for which ButtonVariant to use. 

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.0.1 21A559 darwin-arm, locale en-HU)
    • Flutter version 2.10.4 at /Users/andrastimar/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/andrastimar/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64  • macOS 12.0.1 21A559 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

### LINKED ISSUE #8480: 🐛 [Flutterfire ui] SignIn Screen : ButtonTheme not working
The theme is not applied after package update.

 flutter doctor -v
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale ko-KR)
    • Flutter version 2.10.5 at /Users/patrick386/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (19 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/patrick386/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

스크린샷 2022-04-19 오후 8 38 27

### PR DESCRIPTION
**Pull request by AndrasTimar**
## Description

The PR provides a fix for #8443, by setting the default buttonVariant of the LoadingButton to Outlined. This results in the UI-s using a LoadingButton to behave like they did before #8333 was merged. Before the #8333 was merged, the LoadingButton used to be an OutlinedButton, but in the current implementation it defaults to being a TextButton, which can not be overridden from composite UI elements using a LoadingButton (e.g. EmailForm or SignInScreen). This is poses a problem on these UI elements, because it makes it impossible to style the UI elements seperatly. (In the case of the EmailForm, the Sign in button and the Forgotton password button can only be styled together - Using TextButtonTheme).

## Related Issues

Resolves #8443 
Resolves #8480 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Review by lesnitsky — APPROVED** [review]

**Review by russellwheatley — APPROVED** [review]
LGTM

**Comment by AndrasTimar** [comment]
Left off some trailing commas, please recheck

**Comment by MarcVanDaele90** [comment]
Probably not the best place to ask this, but when will this fix be released?  Will we get a 0.4.0+6 ? if so, by when? 
(my questions sound more harsh than intended, sorry for that)

**Comment by russellwheatley** [comment]
@MarcVanDaele90 hopefully tomorrow 👍

**Comment by MarcVanDaele90** [comment]
@russellwheatley   Thanks for your quick reply!  It's appreciated!

**Comment by MarcVanDaele90** [comment]
> @MarcVanDaele90 hopefully tomorrow +1

I guess there is no release yet containing this fix?  Any ETA?

**Comment by russellwheatley** [comment]
@MarcVanDaele90 My bad, the latest has been released and contains this fix 🙏

**Comment by MarcVanDaele90** [comment]
Thank you!

**Pull request merged**
